/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProfessionRouteImport } from './routes/profession'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MyReelsRouteImport } from './routes/my-reels'
import { Route as FilmRouteImport } from './routes/film'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as EditingRouteImport } from './routes/editing'
import { Route as EditRouteImport } from './routes/edit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsSubscriptionRouteImport } from './routes/settings.subscription'
import { Route as SettingsBrandEditRouteImport } from './routes/settings.brand-edit'
import { Route as SettingsBrandRouteImport } from './routes/settings.brand'
import { Route as ReelIdRouteImport } from './routes/reel.$id'
import { Route as IdeasFormatRouteImport } from './routes/ideas.$format'
import { Route as CategoryIdRouteImport } from './routes/category.$id'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionRoute = ProfessionRouteImport.update({
  id: '/profession',
  path: '/profession',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MyReelsRoute = MyReelsRouteImport.update({
  id: '/my-reels',
  path: '/my-reels',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmRoute = FilmRouteImport.update({
  id: '/film',
  path: '/film',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const EditingRoute = EditingRouteImport.update({
  id: '/editing',
  path: '/editing',
  getParentRoute: () => rootRouteImport,
} as any)
const EditRoute = EditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSubscriptionRoute = SettingsSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsBrandEditRoute = SettingsBrandEditRouteImport.update({
  id: '/brand-edit',
  path: '/brand-edit',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsBrandRoute = SettingsBrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => SettingsRoute,
} as any)
const ReelIdRoute = ReelIdRouteImport.update({
  id: '/reel/$id',
  path: '/reel/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasFormatRoute = IdeasFormatRouteImport.update({
  id: '/ideas/$format',
  path: '/ideas/$format',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryIdRoute = CategoryIdRouteImport.update({
  id: '/category/$id',
  path: '/category/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/edit': typeof EditRoute
  '/editing': typeof EditingRoute
  '/explore': typeof ExploreRoute
  '/film': typeof FilmRoute
  '/my-reels': typeof MyReelsRoute
  '/onboarding': typeof OnboardingRoute
  '/profession': typeof ProfessionRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRouteWithChildren
  '/templates': typeof TemplatesRoute
  '/category/$id': typeof CategoryIdRoute
  '/ideas/$format': typeof IdeasFormatRoute
  '/reel/$id': typeof ReelIdRoute
  '/settings/brand': typeof SettingsBrandRoute
  '/settings/brand-edit': typeof SettingsBrandEditRoute
  '/settings/subscription': typeof SettingsSubscriptionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/edit': typeof EditRoute
  '/editing': typeof EditingRoute
  '/explore': typeof ExploreRoute
  '/film': typeof FilmRoute
  '/my-reels': typeof MyReelsRoute
  '/onboarding': typeof OnboardingRoute
  '/profession': typeof ProfessionRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRouteWithChildren
  '/templates': typeof TemplatesRoute
  '/category/$id': typeof CategoryIdRoute
  '/ideas/$format': typeof IdeasFormatRoute
  '/reel/$id': typeof ReelIdRoute
  '/settings/brand': typeof SettingsBrandRoute
  '/settings/brand-edit': typeof SettingsBrandEditRoute
  '/settings/subscription': typeof SettingsSubscriptionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/edit': typeof EditRoute
  '/editing': typeof EditingRoute
  '/explore': typeof ExploreRoute
  '/film': typeof FilmRoute
  '/my-reels': typeof MyReelsRoute
  '/onboarding': typeof OnboardingRoute
  '/profession': typeof ProfessionRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRouteWithChildren
  '/templates': typeof TemplatesRoute
  '/category/$id': typeof CategoryIdRoute
  '/ideas/$format': typeof IdeasFormatRoute
  '/reel/$id': typeof ReelIdRoute
  '/settings/brand': typeof SettingsBrandRoute
  '/settings/brand-edit': typeof SettingsBrandEditRoute
  '/settings/subscription': typeof SettingsSubscriptionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/edit'
    | '/editing'
    | '/explore'
    | '/film'
    | '/my-reels'
    | '/onboarding'
    | '/profession'
    | '/profile'
    | '/saved'
    | '/settings'
    | '/templates'
    | '/category/$id'
    | '/ideas/$format'
    | '/reel/$id'
    | '/settings/brand'
    | '/settings/brand-edit'
    | '/settings/subscription'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/edit'
    | '/editing'
    | '/explore'
    | '/film'
    | '/my-reels'
    | '/onboarding'
    | '/profession'
    | '/profile'
    | '/saved'
    | '/settings'
    | '/templates'
    | '/category/$id'
    | '/ideas/$format'
    | '/reel/$id'
    | '/settings/brand'
    | '/settings/brand-edit'
    | '/settings/subscription'
  id:
    | '__root__'
    | '/'
    | '/edit'
    | '/editing'
    | '/explore'
    | '/film'
    | '/my-reels'
    | '/onboarding'
    | '/profession'
    | '/profile'
    | '/saved'
    | '/settings'
    | '/templates'
    | '/category/$id'
    | '/ideas/$format'
    | '/reel/$id'
    | '/settings/brand'
    | '/settings/brand-edit'
    | '/settings/subscription'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EditRoute: typeof EditRoute
  EditingRoute: typeof EditingRoute
  ExploreRoute: typeof ExploreRoute
  FilmRoute: typeof FilmRoute
  MyReelsRoute: typeof MyReelsRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfessionRoute: typeof ProfessionRoute
  ProfileRoute: typeof ProfileRoute
  SavedRoute: typeof SavedRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  TemplatesRoute: typeof TemplatesRoute
  CategoryIdRoute: typeof CategoryIdRoute
  IdeasFormatRoute: typeof IdeasFormatRoute
  ReelIdRoute: typeof ReelIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profession': {
      id: '/profession'
      path: '/profession'
      fullPath: '/profession'
      preLoaderRoute: typeof ProfessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-reels': {
      id: '/my-reels'
      path: '/my-reels'
      fullPath: '/my-reels'
      preLoaderRoute: typeof MyReelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/film': {
      id: '/film'
      path: '/film'
      fullPath: '/film'
      preLoaderRoute: typeof FilmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editing': {
      id: '/editing'
      path: '/editing'
      fullPath: '/editing'
      preLoaderRoute: typeof EditingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit': {
      id: '/edit'
      path: '/edit'
      fullPath: '/edit'
      preLoaderRoute: typeof EditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/subscription': {
      id: '/settings/subscription'
      path: '/subscription'
      fullPath: '/settings/subscription'
      preLoaderRoute: typeof SettingsSubscriptionRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/brand-edit': {
      id: '/settings/brand-edit'
      path: '/brand-edit'
      fullPath: '/settings/brand-edit'
      preLoaderRoute: typeof SettingsBrandEditRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/brand': {
      id: '/settings/brand'
      path: '/brand'
      fullPath: '/settings/brand'
      preLoaderRoute: typeof SettingsBrandRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/reel/$id': {
      id: '/reel/$id'
      path: '/reel/$id'
      fullPath: '/reel/$id'
      preLoaderRoute: typeof ReelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas/$format': {
      id: '/ideas/$format'
      path: '/ideas/$format'
      fullPath: '/ideas/$format'
      preLoaderRoute: typeof IdeasFormatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$id': {
      id: '/category/$id'
      path: '/category/$id'
      fullPath: '/category/$id'
      preLoaderRoute: typeof CategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteChildren {
  SettingsBrandRoute: typeof SettingsBrandRoute
  SettingsBrandEditRoute: typeof SettingsBrandEditRoute
  SettingsSubscriptionRoute: typeof SettingsSubscriptionRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsBrandRoute: SettingsBrandRoute,
  SettingsBrandEditRoute: SettingsBrandEditRoute,
  SettingsSubscriptionRoute: SettingsSubscriptionRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditRoute: EditRoute,
  EditingRoute: EditingRoute,
  ExploreRoute: ExploreRoute,
  FilmRoute: FilmRoute,
  MyReelsRoute: MyReelsRoute,
  OnboardingRoute: OnboardingRoute,
  ProfessionRoute: ProfessionRoute,
  ProfileRoute: ProfileRoute,
  SavedRoute: SavedRoute,
  SettingsRoute: SettingsRouteWithChildren,
  TemplatesRoute: TemplatesRoute,
  CategoryIdRoute: CategoryIdRoute,
  IdeasFormatRoute: IdeasFormatRoute,
  ReelIdRoute: ReelIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
